
esphome:
  name: desktop_robot
  platform: ESP32
  board: esp32-s3-devkitc-1

wifi:
  ssid: "your_wifi_ssid"
  password: "your_wifi_password"

api:
  password: "your_api_password"

ota:
  password: "your_ota_password"

logger:

i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO26

microphone:
  - platform: i2s_audio
    id: mic1
    i2s_din_pin: GPIO34

speaker:
  - platform: i2s_audio
    id: spk1
    dac_type: external
    i2s_dout_pin: GPIO22
